quic:
#原
  #initStreamReceiveWindow: 8388608
#  maxStreamReceiveWindow: 8388608
 # initConnReceiveWindow: 20971520
#  maxConnReceiveWindow: 20971520
  initStreamReceiveWindow: 16777216     # 16MB
  maxStreamReceiveWindow: 33554432      # 32MB
  initConnReceiveWindow: 67108864       # 64MB
  maxConnReceiveWindow: 100663296       # 96MB
  maxIdleTimeout: 90s
  maxIncomingStreams: 1024
  disablePathMTUDiscovery: false
ignoreClientBandwidth: false
disableUDP: false
udpIdleTimeout: 180s
resolver:
  type: system
acl:
  inline:
    - direct(geosite:google)
    - reject(geosite:cn)
    - reject(geoip:cn)
masquerade:
  type: 404

